# AUTOGENERATED! DO NOT EDIT! File to edit: ../Lesson2_DeployModel.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'examples', 'intf', 'is_cat', 'classify_image']

# %% ../Lesson2_DeployModel.ipynb 3
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% ../Lesson2_DeployModel.ipynb 6
learn = load_learner('model.pkl')

# %% ../Lesson2_DeployModel.ipynb 8
categories = ('Dog', 'Cat')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% ../Lesson2_DeployModel.ipynb 10
examples = ['dog.jpg', 'cat.jpg', 'dunno.jpg']
intf = gr.Interface(fn=classify_image, inputs=gr.Image(width=192, height=192), outputs=gr.Label(), examples=examples)
intf.launch(inline=False)
